/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2022-11-20 13:08:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import semi.culture.mvc.show.model.vo.Stadium;
import semi.culture.common.util.PageInfo;
import semi.culture.mvc.reviewboard.model.vo.Review;
import semi.culture.mvc.member.model.vo.DipLike;
import java.util.List;
import semi.culture.mvc.show.model.vo.ShowDetail;
import semi.culture.mvc.member.model.vo.Member;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/common/header.jsp", Long.valueOf(1666585171368L));
    _jspx_dependants.put("/views/common/footer.jsp", Long.valueOf(1660793869268L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("semi.culture.mvc.member.model.vo.DipLike");
    _jspx_imports_classes.add("semi.culture.mvc.member.model.vo.Member");
    _jspx_imports_classes.add("semi.culture.mvc.show.model.vo.Stadium");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("semi.culture.mvc.show.model.vo.ShowDetail");
    _jspx_imports_classes.add("semi.culture.mvc.reviewboard.model.vo.Review");
    _jspx_imports_classes.add("semi.culture.common.util.PageInfo");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

     ShowDetail detail = (ShowDetail)request.getAttribute("detail");
    Stadium stadium = (Stadium)request.getAttribute("stadium");
    List<DipLike> dipLike = (List<DipLike>)request.getAttribute("dipLike");
    List<Review> review = (List<Review>)request.getAttribute("review"); 
    List<ShowDetail> detailList = (List<ShowDetail>)request.getAttribute("detailList");
    int result = 0;
    
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
	String path = request.getContextPath();
	Member loginMember = null;
	
	if(session.getAttribute("loginMember")!=null){
		loginMember = (Member)session.getAttribute("loginMember");
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("    <!-- ========Around ============시작-->\r\n");
      out.write("    <!-- SEO Meta Tags-->\r\n");
      out.write("    <meta name=\"description\" content=\"Around - Multipurpose Bootstrap Template\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"bootstrap, business, consulting, coworking space, services, creative agency, dashboard, e-commerce, mobile app showcase, multipurpose, product landing, shop, software, ui kit, web studio, landing, html5, css3, javascript, gallery, slider, touch, creative\">\r\n");
      out.write("    <meta name=\"author\" content=\"Createx Studio\">\r\n");
      out.write("    <!-- Viewport-->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <!-- Favicon and Touch Icons-->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"apple-touch-icon.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"favicon-32x32.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"favicon-16x16.png\">\r\n");
      out.write("    <link rel=\"manifest\" href=\"site.webmanifest\">\r\n");
      out.write("    <link rel=\"mask-icon\" color=\"#5bbad5\" href=\"safari-pinned-tab.svg\">\r\n");
      out.write("    <meta name=\"msapplication-TileColor\" content=\"#766df4\">\r\n");
      out.write("    <meta name=\"theme-color\" content=\"#ffffff\">\r\n");
      out.write("    <!-- Page loading styles-->\r\n");
      out.write("    <style>\r\n");
      out.write("        .page-loading {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            right: 0;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            -webkit-transition: all .4s .2s ease-in-out;\r\n");
      out.write("            transition: all .4s .2s ease-in-out;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("            visibility: hidden;\r\n");
      out.write("            z-index: 9999;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .page-loading.active {\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("            visibility: visible;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .page-loading-inner {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            -webkit-transform: translateY(-50%);\r\n");
      out.write("            transform: translateY(-50%);\r\n");
      out.write("            -webkit-transition: opacity .2s ease-in-out;\r\n");
      out.write("            transition: opacity .2s ease-in-out;\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .page-loading.active>.page-loading-inner {\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .page-loading-inner>span {\r\n");
      out.write("            display: block;\r\n");
      out.write("            font-family: 'Inter', sans-serif;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            font-weight: normal;\r\n");
      out.write("            color: #737491;\r\n");
      out.write("        }\r\n");
      out.write("        /* button 추가 */\r\n");
      out.write("        \r\n");
      out.write("        .button1 {\r\n");
      out.write("            background-color: #9A161F;\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 15px 30px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            margin: 4px 2px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            margin-left: 1100px;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            margin-top: -100px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .button2 {\r\n");
      out.write("            background-color: #9A161F;\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 15px 30px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            margin: 4px 2px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        /* button 추가 */\r\n");
      out.write("        /* div margin 추가 */\r\n");
      out.write("        \r\n");
      out.write("        .marT {\r\n");
      out.write("            margin-top: -30px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        div.mar {\r\n");
      out.write("            margin-left: -85px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        div.mar1 {\r\n");
      out.write("            margin-left: -45px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        div.mar2 {\r\n");
      out.write("            margin-left: -5px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        div.mar3 {\r\n");
      out.write("            margin-left: 35px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        div.mar-top {\r\n");
      out.write("            margin-top: 150px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        div.mar-top-1 {\r\n");
      out.write("            margin-top: 120px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        h5.mar-top {\r\n");
      out.write("            margin-top: -10px;\r\n");
      out.write("            margin-left: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        p.mar-top {\r\n");
      out.write("            margin-top: -10px;\r\n");
      out.write("            margin-left: 35px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .page-spinner {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            width: 2.75rem;\r\n");
      out.write("            height: 2.75rem;\r\n");
      out.write("            margin-bottom: .75rem;\r\n");
      out.write("            vertical-align: text-bottom;\r\n");
      out.write("            border: .15em solid #766df4;\r\n");
      out.write("            border-right-color: transparent;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            -webkit-animation: spinner .75s linear infinite;\r\n");
      out.write("            animation: spinner .75s linear infinite;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        @-webkit-keyframes spinner {\r\n");
      out.write("            100% {\r\n");
      out.write("                -webkit-transform: rotate(360deg);\r\n");
      out.write("                transform: rotate(360deg);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        @keyframes spinner {\r\n");
      out.write("            100% {\r\n");
      out.write("                -webkit-transform: rotate(360deg);\r\n");
      out.write("                transform: rotate(360deg);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        section #enroll-container {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #9A161F;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        section #enroll-container input {\r\n");
      out.write("            margin: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        section #enroll-container table {\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        section #enroll-container table th {\r\n");
      out.write("            padding: 0 10px;\r\n");
      out.write("            text-align: right;\r\n");
      out.write("            font-size: x-large;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        section #enroll-container table td {\r\n");
      out.write("            padding: 0 10px;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <!-- Page loading scripts-->\r\n");
      out.write("    <script>\r\n");
      out.write("        (function() {\r\n");
      out.write("            window.onload = function() {\r\n");
      out.write("                var preloader = document.querySelector('.page-loading');\r\n");
      out.write("                preloader.classList.remove('active');\r\n");
      out.write("                setTimeout(function() {\r\n");
      out.write("                    preloader.remove();\r\n");
      out.write("                }, 2000);\r\n");
      out.write("            };\r\n");
      out.write("        })();\r\n");
      out.write("    </script>\r\n");
      out.write("    <!-- Vendor Styles-->\r\n");
      out.write("    <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.print(path );
      out.write("/vendor/simplebar/dist/simplebar.min.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.print(path );
      out.write("/vendor/tiny-slider/dist/tiny-slider.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.print(path );
      out.write("/vendor/flatpickr/dist/flatpickr.min.css\" />\r\n");
      out.write("    <!-- Main Theme Styles + Bootstrap-->\r\n");
      out.write("    <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.print(path );
      out.write("/css/theme.min.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- =======================around 끝=======================-->\r\n");
      out.write("\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(path );
      out.write("/style.css\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <title>cultureshock</title>\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/b4c02836de.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.print(path );
      out.write("/dist/vendor/flatpickr/dist/flatpickr.min.css\" />\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/b4c02836de.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <!-- <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor\" crossorigin=\"anonymous\"> -->\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <!-- 나의 js 코드 -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("     <script>\r\n");
      out.write("        function reserveZoneOn() {\r\n");
      out.write("            $('#reserveZone').css('display', 'block').addClass('.show');\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // function completeSelect() {\r\n");
      out.write("\r\n");
      out.write("        // }\r\n");
      out.write("\r\n");
      out.write("        function openImage() {\r\n");
      out.write("            window.open('https://www.kopis.or.kr/upload/pfmIntroImage/PF_PF194394_220711_0123230.jpg', 'detail', 'width=500px, height=500px')\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"page-loading active\">\r\n");
      out.write("        <div class=\"page-loading-inner\">\r\n");
      out.write("            <div class=\"page-spinner\"></div><span>Loading...</span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ==============헤더시작=============== -->\r\n");
      out.write("    <header>\r\n");
      out.write("        <nav class=\"navbar_custom\">\r\n");
      out.write("            <div class=\"navbar_logo_custom\" style=\"margin-left: 150px; padding: bottom 80px;\">\r\n");
      out.write("                <a href=\"");
      out.print(path );
      out.write("/main2\"> \r\n");
      out.write("                    <img src=\"logo_ver3.svg\" class=\"navbar-brand-logo_custom\" style=\"width:120px; height:120px;\">\r\n");
      out.write("                </a>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <nav class=\"navbar_menu_custom\" style=\"margin-bottom:-60px; \">\r\n");
      out.write("                <ul class=\"navbar_menu_custom\">\r\n");
      out.write("                    <li class=\"nav-item \"><a href=\"");
      out.print(path );
      out.write("/main2\">홈</a></li> \r\n");
      out.write("                    <li class=\"nav-item \"><a href=\"");
      out.print(path );
      out.write("/musical\">뮤지컬</a></li> \r\n");
      out.write("                    <li class=\"nav-item\"><a href=\"");
      out.print(path );
      out.write("/drama\">연극</a></li>\r\n");
      out.write("                    <li class=\"nav-item \"><a href=\"");
      out.print(path );
      out.write("/classic\">클래식</a></li>\r\n");
      out.write("                    <li class=\"nav-item \"><a href=\"");
      out.print(path );
      out.write("/korean\">국악</a></li>\r\n");
      out.write("                    <li class=\"nav-item dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle\" role=\"button\" id=\"board\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">게시판</a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\" aria-labelledby=\"board\">\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"");
      out.print(path );
      out.write("/notice_list\">공지게시판</a></li> \r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"");
      out.print(path );
      out.write("/review_list\">리뷰게시판</a></li> \r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"");
      out.print(path );
      out.write("/QnA_list\">문의게시판</a></li> \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"navbar_icons_custom \" style=\"margin-top:-60px;\">\r\n");
      out.write("            \t");
 if(loginMember != null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"h5 mt-2\">");
      out.print(loginMember.getUser_name() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t님 반갑습니다\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t");
} else { 
      out.write("\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <a href=\"");
      out.print(path );
      out.write("/login\">\r\n");
      out.write("\t                        <i class=\"fa-solid fa-user\"></i>\r\n");
      out.write("\t                    </a>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <a href=\"");
      out.print(path );
      out.write("/enroll\">\r\n");
      out.write("\t                        <i class=\"fa-solid fa-user-plus\"></i>\r\n");
      out.write("\t                    </a>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t            ");
} 
      out.write("\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"dropdown-toggle\" role=\"button\" id=\"myPage\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">마이페이지</a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\" aria-labelledby=\"myPage\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print(path );
      out.write("/myPage\">마이페이지 메인</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print(path );
      out.write("/Memberupdate\">회원정보수정</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print(path );
      out.write("/bookCompleteList\">예매내역</a></li>\r\n");
      out.write("                        ");
 if(loginMember != null){ 
      out.write("\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print(path );
      out.write("/logout\">로그아웃</a></li>\r\n");
      out.write("                        ");
} 
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- ===================헤더끝=====================-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <body>");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- <img src=\"./resources/d_all_2.svg\" style=\"height: 70%;\" alt=\"\"> -->\r\n");
      out.write("    <section class=\"m-lg-5\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container  mb-md-5 mt-3\">\r\n");
      out.write("            <img src=\"");
      out.print(path);
      out.write("/resources/dblquote.svg\" class=\"mb-3\" alt=\"\">\r\n");
      out.write("            <p class=\"h3 fw-bold mb-4 \" style=\"color: #9A161F; \">\r\n");
      out.write("                ");
      out.print(detail.getPrfnm() );
      out.write("\r\n");
      out.write("            </p>\r\n");
      out.write("            <div class=\"float-end\">\r\n");
      out.write("                <button class=\"btn-info btn\" style=\"background-color: #9A161F; border: #9A161F solid; color:white;\" onclick=\"reserveZoneOn()\">\r\n");
      out.write("                    예매하기\r\n");
      out.write("                </button>\r\n");
      out.write("                ");
 
                   if(loginMember != null) {
                    for(int i = 0; i < dipLike.size(); i++){
						if(dipLike.get(i).getPrfid().equals(detail.getPrfid())){ // 같은 찜 목록 있다면
							result = 1;
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("                <button class=\"btn-info btn\" style=\"background-color: #9A161F; border: #9A161F solid; color:white;\" onclick=\"location.href='");
      out.print(path);
      out.write("/DeleteDipLike?prfid=");
      out.print(detail.getPrfid() );
      out.write("';\"  >\r\n");
      out.write("                   찜 삭제♥ \r\n");
      out.write("                   </button>\r\n");
      out.write("\t\t\t\t\t");
	
							}
                    }
                   }
						
      out.write("\r\n");
      out.write("                   \t\t");
if(result == 0) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn-info btn\" style=\"background-color: #9A161F; border: #9A161F solid; color:white;\" onclick=\"DipLike();\"  >\r\n");
      out.write("                   \t\t찜 하기♡ \r\n");
      out.write("                   \t\t</button>\r\n");
      out.write("                   \t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("                  <script type=\"text/javascript\">\r\n");
      out.write("                  function DipLike() {\r\n");
      out.write("\t\t\t\t\t");
 if (loginMember == null){
      out.write("\r\n");
      out.write("\t\t\t\t\talert(\"로그인 후 이용해주세요!\");\r\n");
      out.write("\t\t\t\t\t");
 } else {
      out.write("\r\n");
      out.write("\t\t\t\t\tlocation.href='");
      out.print(path);
      out.write("/InsertDipLike?prfid=");
      out.print(detail.getPrfid() );
      out.write("';\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("                  </script>\r\n");
      out.write("                    \r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <div class=\"container w-75\" style=\"width: fit-content;\">\r\n");
      out.write("            <!-- Nav tabs -->\r\n");
      out.write("            <ul class=\"nav nav-tabs justify-content-start\" role=\"tablist\" style=\"width: 100%;\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"#infoDetail\" class=\"nav-link active\" data-bs-toggle=\"tab\" role=\"tab\">\r\n");
      out.write("                        상세 정보\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"#story\" class=\"nav-link\" data-bs-toggle=\"tab\" role=\"tab\">\r\n");
      out.write("                        스토리\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <!-- Tabs content -->\r\n");
      out.write("            <div class=\"tab-content border-bottom  \">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"tab-pane fade show active\" id=\"infoDetail\" role=\"tabpanel\">\r\n");
      out.write("                    <div class=\"row \">\r\n");
      out.write("                        <div class=\"col-md-3\">\r\n");
      out.write("                            <img src=\"");
      out.print(detail.getPoster());
      out.write("\" alt=\"\" style=\"height: 100%;\">\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-9 \">\r\n");
      out.write("                            <div class=\"table-responsive pt-3\">\r\n");
      out.write("                                <table class=\"table-sm\">\r\n");
      out.write("                                    <tbody>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <th>공연기간 </th>\r\n");
      out.write("                                            <td>");
      out.print(detail.getPrfpdfrom());
      out.write(' ');
      out.write('~');
      out.write(' ');
      out.print(detail.getPrfpdto());
      out.write("</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <th>공연장소</th>\r\n");
      out.write("                                            <td> ");
      out.print(detail.getFcltynm());
      out.write("</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <th>공연시간 </th>\r\n");
      out.write("                                            <td>");
      out.print(detail.getTimedtguidance() );
      out.write("</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <th>관람연령 </th>\r\n");
      out.write("                                            <td>");
      out.print(detail.getPrfage());
      out.write("</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <th>티켓가격 </th> \r\n");
      out.write("                                            <td>");
      out.print(detail.getPcseguidance());
      out.write("</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <th>출연진 </th>\r\n");
      out.write("                                            <td>");
 if(detail.getPrfcast() == null) {
													out.println("해당 정보 없음");				
                                            } else {
                                            	
      out.write("\r\n");
      out.write("                                            \t");
      out.print(detail.getPrfcast() );
      out.write("\r\n");
      out.write("                                            ");
 } 
      out.write("\r\n");
      out.write("                                            \t</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        <tfoot>\r\n");
      out.write("                                        </tfoot>\r\n");
      out.write("                                    </tbody>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"tab-pane fade \" id=\"story\" role=\"tabpanel\">\r\n");
      out.write("                    <div class=\"row text-start\">\r\n");
      out.write("                        <div class=\"col-md-3 justify-content-center\">\r\n");
      out.write("                            <img src=\"");
      out.print(detail.getPoster() );
      out.write("\" alt=\"\">\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-9 pt-5  p-2\">\r\n");
      out.write("\r\n");
      out.write("                            <p>\r\n");
      out.write("                                ");
 if(detail.getSty() == null) {
                                	out.println("해당 정보 없음");
                                } else {
                                	out.println(detail.getSty());
                                }
                                
                                
      out.write("\r\n");
      out.write("                            </p>\r\n");
      out.write("\r\n");
      out.write("                            <!-- <button type=\"button\" class=\"btn btn-outline-dark float-end\" onclick=\"\">이야기 더보기</button> -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!--예약시작-->\r\n");
      out.write("        <form action=\"");
      out.print( path);
      out.write("/ticketInsert?prfid=");
      out.print(detail.getPrfid() );
      out.write("\" method=\"get\">\r\n");
      out.write("        <input type=\"hidden\" name=\"prfid\" value=\"");
      out.print(detail.getPrfid());
      out.write("\">\r\n");
      out.write("        <input type=\"hidden\" name=\"prfnm\" value=\"");
      out.print(detail.getPrfnm());
      out.write("\">\r\n");
      out.write("        <div class=\"container mt-3  w-75\" id=\"reserveZone\" style=\"display: none;width: 100%;\">\r\n");
      out.write("            <img src=\"");
      out.print(path);
      out.write("/resources/1000x250_4.svg\" alt=\"\" style=\"height: 50%;\">\r\n");
      out.write("            <div class=\"continer border\">\r\n");
      out.write("                <div class=\"row \">\r\n");
      out.write("                    <div class=\"col-8 p-3 m-3 border-end \">\r\n");
      out.write("                        <div class=\"text-center border-bottom py-2 my-2\">\r\n");
      out.write("                            <p class=\"text-muted\"> 예매자는 본 안내페이지의 모든 내용을 숙지 및 동의한 것으로 간주합니다. <br> 관람 연령,티켓 수령, 공연 관람 안내 미숙지로 인한 책임은 관람자 본인에게 있으며,<br> 예매 티켓의 취소/변경/환불은 불가하오니 이 점 유의 바랍니다.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\" py-2\">\r\n");
      out.write("                            <div class=\"h4 mb-3 pb-3 border-bottom text-center\" style=\"color:#9A161F\">예매내용</div>\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-5 border-end\">\r\n");
      out.write("                                    <img src=\"https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMTA5MTRfMTkx%2FMDAxNjMxNTg2MDY3Mjk0.QkbXdvtbL6Gq2iE88BoIDuEqCWXQ6HlzKlFmu2TVioAg.xity1ljDDgC7-s69FjYv57OR3zRhkTn4wRtCD8cIYVIg.JPEG.motetpark%2F123456.jpg&type=sc960_832\"\r\n");
      out.write("                                        alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-6 ps-3\">\r\n");
      out.write("                                    <!-- Date picker -->\r\n");
      out.write("                                    <div class=\"mb-2\">\r\n");
      out.write("                                        <label class=\"form-label text-start\">공연일</label>\r\n");
      out.write("                                        <div class=\"input-group align-items-center\" style=\"width: 90%;\">\r\n");
      out.write("                                            <input class=\"form-control date-picker rounded pe-5\" onchange=\"change_day(this.value);\" type=\"text\" id=\"day\" name=\"day\" placeholder=\"Choose date\" data-datepicker-options='{\"altInput\": true, \"altFormat\": \"F j, Y\", \"dateFormat\": \"Y-m-d\"}'>\r\n");
      out.write("                                            <i class=\"ai-calendar position-absolute top-50 end-0 translate-middle-y me-3\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- Inline radio buttons -->\r\n");
      out.write("                                    <p class=\"form-label text-start\">관객정보</p>\r\n");
      out.write("                                    <!-- Inline checkboxes -->\r\n");
      out.write("                                    <div class=\"form-check form-check-inline\">\r\n");
      out.write("                                        <input class=\"form-check-input\" type=\"radio\" id=\"adult\" name=\"type\" value=\"adult\">\r\n");
      out.write("                                        <label class=\"form-check-label\" for=\"adult\">성인</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-check form-check-inline\">\r\n");
      out.write("                                        <input class=\"form-check-input\" type=\"radio\" id=\"juv\" name=\"type\" value=\"juv\">\r\n");
      out.write("                                        <label class=\"form-check-label\" for=\"juv\">청소년</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-check form-check-inline mb-2\">\r\n");
      out.write("                                        <input class=\"form-check-input\" type=\"radio\" id=\"child\" name=\"type\" value=\"child\">\r\n");
      out.write("                                        <label class=\"form-check-label\" for=\"child\">어린이</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <p class=\"form-label text-start \">인원</p>\r\n");
      out.write("                                    <div class=\"inline input-group-sm  mb-2\" style=\"width: 85%;\">\r\n");
      out.write("                                        <select class=\"form-select\" id=\"nmPersonCh\" name=\"peopleCount\" onchange=\"change_count(this.value); total(this.form.nmPersonCh.value, this.form.seatInfo.value);\">\r\n");
      out.write("                                                <option value=\"1\">1</option>\r\n");
      out.write("                                                <option value=\"2\">2</option>\r\n");
      out.write("                                                <option value=\"3\">3</option>\r\n");
      out.write("                                                <option value=\"4\">4</option>\r\n");
      out.write("                                                <option value=\"5\">5</option>\r\n");
      out.write("                                                <option value=\"6\">6</option>\r\n");
      out.write("                                            </select>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <p class=\"form-label text-start\">좌석정보</p>\r\n");
      out.write("                                    ");
 
                                    String seat = detail.getPcseguidance(); 
                                    
                                    
      out.write("\r\n");
      out.write("                                    <div class=\"inline input-group-sm\" style=\"width: 85%;\">\r\n");
      out.write("                                        <select class=\"form-select\" id=\"nmPersonCh\" name=\"seatInfo\" onchange=\"change_seat(this.value); total(this.form.nmPersonCh.value, this.form.seatInfo.value);\">\r\n");
      out.write("                                                <option value=\"0\">--좌석 선택--</option>\r\n");
      out.write("                                                ");
 if(seat.contains("R석")){ 
                                                String[] seatArr = seat.split(", ");
                                                
                                                
                                                for(int i = 0; i < seatArr.length; i++) {
                                                	
                                                
      out.write("\r\n");
      out.write("                                                <option value=\"");
      out.print(seatArr[i].substring(seatArr[i].indexOf("석")+1).replace(",", "").replace("원", "") );
      out.write('"');
      out.write('>');
      out.print(seatArr[i] );
      out.write("</option>\r\n");
      out.write("                                               <!--   \t<option value=\"50000\">S석 50,000원</option>\r\n");
      out.write("                                                \t\t<option value=\"30000\">A석 30,000원</option>\r\n");
      out.write("                                                \t\t<option value=\"10000\">B석 10,000원</option> -->\r\n");
      out.write("                                                \t\t");
 } 
      out.write("\r\n");
      out.write("                                                ");
} else if(seat.contains("무료")) { 
      out.write("\r\n");
      out.write("                                                <option value=\"0\">");
      out.print(seat );
      out.write("</option>\r\n");
      out.write("                                                ");
} else if(seat.contains("전석")) {
      out.write("\r\n");
      out.write("                                                <option value=\"");
      out.print(seat.substring(3).replace(",", "").replace("원", ""));
      out.write('"');
      out.write('>');
      out.print(seat );
      out.write("</option>                             \r\n");
      out.write("                                                ");
} 
      out.write("\r\n");
      out.write("                                            </select>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                  \t<!--   <button class=\"mt-3 btn btn-outline-primary d-block w-25\" onclick=\"completeSelect();\">선택완료</button> -->\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"col-3\">\r\n");
      out.write("                        <!-- Vertical pricing plan: Border -->\r\n");
      out.write("                        <div class=\" container m-4 pt-7\">\r\n");
      out.write("                            <div class=\"container mb-3\">\r\n");
      out.write("                                <h3 class=\"h3\">결제 정보</h3>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <ul class=\"list-unstyled py-2 mb-4\">\r\n");
      out.write("                                <li class=\"d-flex align-items-center mb-3\">\r\n");
      out.write("                                    <i class=\"ai-check fs-xl text-primary me-2\"></i> 결제 금액 : <span id=\"priceTotal\">0</span>원\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"d-flex align-items-center mb-3\">\r\n");
      out.write("                                    <i class=\"ai-check fs-xl text-primary me-2\"></i> 공연일 : <span id=\"dayCh\"></span>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"d-flex align-items-center mb-3\">\r\n");
      out.write("                                    <i class=\"ai-check fs-xl text-primary me-2\"></i> 총 인원 : <span id=\"pcount\">0</span>명\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"d-flex align-items-center mb-3\">\r\n");
      out.write("                                    <i class=\"ai-check fs-xl text-primary me-2\"></i> 좌석당 가격 : <span id=\"seatGrade\"></span>\r\n");
      out.write("                                </li>\r\n");
      out.write("\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <div class=\"text-center mb-2\">\r\n");
      out.write("                                <div class=\"text-sm-end\"><a class=\"btn btn-outline-primary d-block w-100\" href=\"#add-payment\" data-bs-toggle=\"modal\">결제하러 가기</a></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <script>\r\n");
      out.write("            var count = 0;\r\n");
      out.write("            var price = 0;\r\n");
      out.write("            function change_count(value) {\r\n");
      out.write("                document.getElementById(\"pcount\").innerHTML = value;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("              \tcount = value;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function change_seat(value) {\r\n");
      out.write("                document.getElementById(\"seatGrade\").innerHTML = value;\r\n");
      out.write("                \r\n");
      out.write("              price = value;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function change_day(value) {\r\n");
      out.write("                document.getElementById(\"dayCh\").innerHTML = value;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function total(count_value, price_value) {\r\n");
      out.write("            \tvar total =  count * price\r\n");
      out.write("                document.getElementById(\"priceTotal\").innerHTML = total;\r\n");
      out.write("                document.getElementById(\"priceTotal\").value = total;\r\n");
      out.write("            }\r\n");
      out.write("        </script>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <div class=\"modal fade\" id=\"add-payment\">\r\n");
      out.write("            <div class=\"modal-dialog modal-lg modal-dialog-centered\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"modal-header\">\r\n");
      out.write("                        <h4 class=\"modal-title\">결제</h4>\r\n");
      out.write("                        <button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"modal-body\">\r\n");
      out.write("                        <div class=\"form-check mb-4\">\r\n");
      out.write("                            <input class=\"form-check-input\" type=\"radio\" id=\"card\" name=\"payment-method\" checked>\r\n");
      out.write("                            <label class=\"form-check-label\" for=\"card\" data-bs-toggle=\"radioTab\" data-bs-target=\"#card-payment\" data-bs-parent=\"#payment-methods\">Credit / Debit card<img class=\"d-inline-block align-middle ms-2\" src=\"");
      out.print(path );
      out.write("/img/account/cards/cards.png\" alt=\"Cards accepted\" width=\"187\"></label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"pt-3\" id=\"payment-methods\" style=\"text-align: -webkit-center;\">\r\n");
      out.write("                            <div class=\"radio-tab-pane active\" id=\"card-payment\">\r\n");
      out.write("                                <form class=\"row g-0 mx-n2\">\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"mb-3 pb-1 col-sm-6 px-2\">\r\n");
      out.write("                                        <label class=\"form-label\" for=\"cc-number\">Card number</label>\r\n");
      out.write("                                        <input class=\"form-control\" type=\"text\" id=\"cc-number\" placeholder=\"0000 0000 0000 0000\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"mb-3 pb-1 col-sm-6 px-2\">\r\n");
      out.write("                                        <label class=\"form-label\" for=\"cc-holder-name\">Name on card</label>\r\n");
      out.write("                                        <input class=\"form-control\" type=\"text\" id=\"cc-holder-name\" placeholder=\"Card holder's name\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"mb-3 pb-1 col-sm-3 px-2\">\r\n");
      out.write("                                        <label class=\"form-label\" for=\"cc-expiry\">Expiry</label>\r\n");
      out.write("                                        <input class=\"form-control\" type=\"text\" id=\"cc-expiry\" placeholder=\"mm/yy\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"mb-3 pb-1 col-sm-3 px-2\">\r\n");
      out.write("                                        <label class=\"form-label\" for=\"cc-cvc\">CVC</label>\r\n");
      out.write("                                        <input class=\"form-control\" type=\"text\" id=\"cc-cvc\" placeholder=\"000\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"mb-3 pb-1 col-sm-3 px-2\">\r\n");
      out.write("                                        <label class=\"form-label\" for=\"cc-password\">Password</label>\r\n");
      out.write("                                        <input class=\"form-control\" type=\"password\" id=\"password\" placeholder=\"****\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                                <div class=\"col-sm-6 pt-4 px-2\">\r\n");
      out.write("                                    <button class=\"btn btn-primary d-block w-100 mt-1\" type=\"submit\">결제하기</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("        <!--예약끝-->\r\n");
      out.write("        <div class=\"container mt-3 text-center border-bottom\">\r\n");
      out.write("\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-light mb-3 fw-semibold\" data-toggle=\"collapse\" data-target=\"#demo\" style=\"width: 100%;\">▼상세이미지를 확인하려면 클릭하세요.▼</button>\r\n");
      out.write("            <div id=\"demo\" class=\"collapse pb-3\">\r\n");
      out.write("                <img src=\"");
      out.print( detail.getStyurls());
      out.write("\" alt=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container mt-lg-2\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col mt-5 \" style=\"width:500px; height: auto;\">\r\n");
      out.write("                    <div class=\"text-center p-2\">\r\n");
      out.write("                        <p class=\"h3 mb-3\" style=\"color: #9A161F;\">작품리뷰</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Actionalbe list group -->\r\n");
      out.write("                    <div class=\"list-group \">\r\n");
      out.write("                     \t");
 
                    	if(review != null) {
                    		for(int i =0; i < review.size(); i++) {
      out.write("\r\n");
      out.write("                    \t\t\t<a href=\"");
      out.print(path );
      out.write("/review_view?reviewNum=");
      out.print(review.get(i).getReviewnum() );
      out.write(" \" class=\"list-group-item list-group-item-action \">");
      out.print(review.get(i).getRtitle() );
      out.write("</a>\r\n");
      out.write("                    \t");
	}
                    	} 
                    	
      out.write(" <a href=\"# \" class=\"list-group-item list-group-item-action \">리뷰가 없습니다.</a>\r\n");
      out.write("                    \t\r\n");
      out.write("                    \t\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- 지도 시작 -->\r\n");
      out.write("                 <script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=dda3c54a7d81d32069b09462383531c1\"></script>\r\n");
      out.write("                <div class=\"col mt-5\">\r\n");
      out.write("                    <div class=\"text-center p-2\">\r\n");
      out.write("                        <p class=\"h3 mb-3\" style=\"color: #9A161F;\">공연장위치</p>\r\n");
      out.write("                    </div> \r\n");
      out.write("                <!-- 지도 -->\r\n");
      out.write("                  <div id=\"map\" style=\"width:500px;height:400px;\"></div> \r\n");
      out.write("\r\n");
      out.write("                 <script type=\"text/javascript\" src=\"http://dapi.kakao.com/v2/maps/sdk.js?appkey=cf45196fdd120992587a95ae3882e9f3\"></script> \r\n");
      out.write("                <script>\r\n");
      out.write("                        var mapContainer = document.getElementById('map'), // 지도를 표시할 div \r\n");
      out.write("                            mapOption = {\r\n");
      out.write("                                center: new kakao.maps.LatLng(");
      out.print(stadium.getLa() );
      out.write(',');
      out.write(' ');
      out.print(stadium.getLo() );
      out.write("), // 지도의 중심좌표\r\n");
      out.write("                                level: 3 // 지도의 확대 레벨\r\n");
      out.write("                            };\r\n");
      out.write("\r\n");
      out.write("                        var map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다\r\n");
      out.write("\r\n");
      out.write("                        // 마커가 표시될 위치입니다 \r\n");
      out.write("                        var markerPosition = new kakao.maps.LatLng(");
      out.print(stadium.getLa() );
      out.write(',');
      out.write(' ');
      out.print(stadium.getLo() );
      out.write(");\r\n");
      out.write("\r\n");
      out.write("                        // 마커를 생성합니다\r\n");
      out.write("                        var marker = new kakao.maps.Marker({\r\n");
      out.write("                            position: markerPosition\r\n");
      out.write("                        });\r\n");
      out.write("\r\n");
      out.write("                        // 마커가 지도 위에 표시되도록 설정합니다\r\n");
      out.write("                        marker.setMap(map);\r\n");
      out.write("\r\n");
      out.write("                        // 아래 코드는 지도 위의 마커를 제거하는 코드입니다\r\n");
      out.write("                        // marker.setMap(null);\r\n");
      out.write("                    </script> \r\n");
      out.write("\t\t\t\t\t<!-- 지도 끝 -->\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("                </div> \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Related projects (Carousel)-->\r\n");
      out.write("        <div class=\"container py-3 py-lg-6 mb-4 mt-6\">\r\n");
      out.write("            <div class=\"container py-3 py-md-0\">\r\n");
      out.write("                <h3 class=\"h3 text-center mb-6\" style=\"color: #9A161F;\">공연 중인 클래식</h3>\r\n");
      out.write("                <div class=\"tns-carousel-wrapper\">\r\n");
      out.write("                    <div class=\"tns-carousel-inner\" data-carousel-options=\"{&quot;items&quot;: 2, &quot;controls&quot;: false, &quot;nav&quot;: true, &quot;responsive&quot;: {&quot;0&quot;:{&quot;items&quot;:1, &quot;gutter&quot;: 16},&quot;500&quot;:{&quot;items&quot;:2, &quot;gutter&quot;: 16}, &quot;780&quot;:{&quot;items&quot;:3, &quot;gutter&quot;: 16}, &quot;1000&quot;:{&quot;items&quot;:4, &quot;gutter&quot;: 23}}}\">\r\n");
      out.write("                       ");
 for(int i = 0; i < 7; i++){
                    	   
      out.write("\r\n");
      out.write("                       <!-- Item-->\r\n");
      out.write("                        <div class=\"pb-2\">\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <a href=\"");
      out.print(path);
      out.write("/showSelect?prfid=");
      out.print(detailList.get(i).getPrfid() );
      out.write("\"><img class=\"card-img\" style=\"height: 400px; width: 400px;\" src=\"");
      out.print(detailList.get(i).getPoster() );
      out.write("\" alt=\"Portfolio thumb\"></a>\r\n");
      out.write("                             </div>\r\n");
      out.write("                        </div>  \r\n");
      out.write("                          ");
 } 
      out.write(" \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ===================푸터 시작================-->\r\n");
      out.write("    <footer>\r\n");
      out.write("        <nav class=\"foot_custom\">\r\n");
      out.write("            <ul class=\"foot_icons_custom\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"https://facebook.com\" target=\"_blank\">\r\n");
      out.write("                        <i class=\"fa-brands fa-facebook\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"https://google.com\" target=\"_blank\">\r\n");
      out.write("                        <i class=\"fa-brands fa-google\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"https://twitter.com\" target=\"_blank\">\r\n");
      out.write("                        <i class=\"fa-brands fa-twitter\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"https://github.com\" target=\"_blank\">\r\n");
      out.write("                        <i class=\"fa-brands fa-github\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <br/><br/>\r\n");
      out.write("            <h3 style=\"color:#F4EFEA;\">COPYRIGHT ⓒ KOREA PERFORMING ARTS BOX OFFICE INFORMATION SYSTEM</h3>\r\n");
      out.write("            <h6 style=\"color:#F4EFEA;\"> When you visit or interact with our sites, services or tools, we or our authorized<br/> service providers may use cookies for storing information to help provide you with a <br/> better, faster and safer experience and for marketing purposes.</h6>\r\n");
      out.write("            <br/>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- ================== 푸터 끝 ==================-->\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js\" integrity=\"sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js\" integrity=\"sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- JS Implementing Plugins -->\r\n");
      out.write("    <script src=\"./assets/vendor/hs-mega-menu/dist/hs-mega-menu.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- JS Global Compulsory -->\r\n");
      out.write("    <script src=\"./assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"vendor/imagesloaded/imagesloaded.pkgd.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/shufflejs/dist/shuffle.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/parallax-js/dist/parallax.min.js\"></script>\r\n");
      out.write("    <!-- Vendor scrits: js libraries and plugins-->\r\n");
      out.write("    <script src=\"vendor/bootstrap/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/simplebar/dist/simplebar.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/jarallax/dist/jarallax.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/tiny-slider/dist/min/tiny-slider.js\"></script>\r\n");
      out.write("    <script src=\"vendor/flatpickr/dist/flatpickr.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/flatpickr/dist/plugins/rangePlugin.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"vendor/tiny-slider/dist/min/tiny-slider.js\"></script>\r\n");
      out.write("    <script src=\"vendor/lightgallery.js/dist/js/lightgallery.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/lg-video.js/dist/lg-video.min.js\"></script>\r\n");
      out.write("    <!-- Main theme script-->\r\n");
      out.write("    <script src=\"js/theme.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write('	');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
