/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2022-11-20 13:07:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Arrays;
import java.text.SimpleDateFormat;
import javax.lang.model.util.SimpleAnnotationValueVisitor14;
import java.util.Date;
import semi.culture.mvc.show.model.vo.ShowDetail;
import semi.culture.mvc.qnaboard.model.vo.Qna;
import semi.culture.mvc.noticeboard.model.vo.Notice;
import semi.culture.mvc.reviewboard.model.vo.Review;
import semi.culture.mvc.show.model.vo.ShowRank;
import java.util.List;
import semi.culture.mvc.member.model.vo.Member;

public final class main2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/common/header.jsp", Long.valueOf(1666585171368L));
    _jspx_dependants.put("/views/common/footer.jsp", Long.valueOf(1660793869268L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.lang.model.util.SimpleAnnotationValueVisitor14");
    _jspx_imports_classes.add("semi.culture.mvc.member.model.vo.Member");
    _jspx_imports_classes.add("java.util.Arrays");
    _jspx_imports_classes.add("semi.culture.mvc.show.model.vo.ShowDetail");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("semi.culture.mvc.show.model.vo.ShowRank");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("semi.culture.mvc.noticeboard.model.vo.Notice");
    _jspx_imports_classes.add("semi.culture.mvc.qnaboard.model.vo.Qna");
    _jspx_imports_classes.add("semi.culture.mvc.reviewboard.model.vo.Review");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
	String path = request.getContextPath();
	Member loginMember = null;
	
	if(session.getAttribute("loginMember")!=null){
		loginMember = (Member)session.getAttribute("loginMember");
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("    <!-- ========Around ============시작-->\r\n");
      out.write("    <!-- SEO Meta Tags-->\r\n");
      out.write("    <meta name=\"description\" content=\"Around - Multipurpose Bootstrap Template\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"bootstrap, business, consulting, coworking space, services, creative agency, dashboard, e-commerce, mobile app showcase, multipurpose, product landing, shop, software, ui kit, web studio, landing, html5, css3, javascript, gallery, slider, touch, creative\">\r\n");
      out.write("    <meta name=\"author\" content=\"Createx Studio\">\r\n");
      out.write("    <!-- Viewport-->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <!-- Favicon and Touch Icons-->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"apple-touch-icon.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"favicon-32x32.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"favicon-16x16.png\">\r\n");
      out.write("    <link rel=\"manifest\" href=\"site.webmanifest\">\r\n");
      out.write("    <link rel=\"mask-icon\" color=\"#5bbad5\" href=\"safari-pinned-tab.svg\">\r\n");
      out.write("    <meta name=\"msapplication-TileColor\" content=\"#766df4\">\r\n");
      out.write("    <meta name=\"theme-color\" content=\"#ffffff\">\r\n");
      out.write("    <!-- Page loading styles-->\r\n");
      out.write("    <style>\r\n");
      out.write("        .page-loading {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            right: 0;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            -webkit-transition: all .4s .2s ease-in-out;\r\n");
      out.write("            transition: all .4s .2s ease-in-out;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("            visibility: hidden;\r\n");
      out.write("            z-index: 9999;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .page-loading.active {\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("            visibility: visible;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .page-loading-inner {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            -webkit-transform: translateY(-50%);\r\n");
      out.write("            transform: translateY(-50%);\r\n");
      out.write("            -webkit-transition: opacity .2s ease-in-out;\r\n");
      out.write("            transition: opacity .2s ease-in-out;\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .page-loading.active>.page-loading-inner {\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .page-loading-inner>span {\r\n");
      out.write("            display: block;\r\n");
      out.write("            font-family: 'Inter', sans-serif;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            font-weight: normal;\r\n");
      out.write("            color: #737491;\r\n");
      out.write("        }\r\n");
      out.write("        /* button 추가 */\r\n");
      out.write("        \r\n");
      out.write("        .button1 {\r\n");
      out.write("            background-color: #9A161F;\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 15px 30px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            margin: 4px 2px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            margin-left: 1100px;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            margin-top: -100px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .button2 {\r\n");
      out.write("            background-color: #9A161F;\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 15px 30px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            margin: 4px 2px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        /* button 추가 */\r\n");
      out.write("        /* div margin 추가 */\r\n");
      out.write("        \r\n");
      out.write("        .marT {\r\n");
      out.write("            margin-top: -30px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        div.mar {\r\n");
      out.write("            margin-left: -85px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        div.mar1 {\r\n");
      out.write("            margin-left: -45px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        div.mar2 {\r\n");
      out.write("            margin-left: -5px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        div.mar3 {\r\n");
      out.write("            margin-left: 35px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        div.mar-top {\r\n");
      out.write("            margin-top: 150px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        div.mar-top-1 {\r\n");
      out.write("            margin-top: 120px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        h5.mar-top {\r\n");
      out.write("            margin-top: -10px;\r\n");
      out.write("            margin-left: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        p.mar-top {\r\n");
      out.write("            margin-top: -10px;\r\n");
      out.write("            margin-left: 35px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .page-spinner {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            width: 2.75rem;\r\n");
      out.write("            height: 2.75rem;\r\n");
      out.write("            margin-bottom: .75rem;\r\n");
      out.write("            vertical-align: text-bottom;\r\n");
      out.write("            border: .15em solid #766df4;\r\n");
      out.write("            border-right-color: transparent;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            -webkit-animation: spinner .75s linear infinite;\r\n");
      out.write("            animation: spinner .75s linear infinite;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        @-webkit-keyframes spinner {\r\n");
      out.write("            100% {\r\n");
      out.write("                -webkit-transform: rotate(360deg);\r\n");
      out.write("                transform: rotate(360deg);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        @keyframes spinner {\r\n");
      out.write("            100% {\r\n");
      out.write("                -webkit-transform: rotate(360deg);\r\n");
      out.write("                transform: rotate(360deg);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        section #enroll-container {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #9A161F;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        section #enroll-container input {\r\n");
      out.write("            margin: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        section #enroll-container table {\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        section #enroll-container table th {\r\n");
      out.write("            padding: 0 10px;\r\n");
      out.write("            text-align: right;\r\n");
      out.write("            font-size: x-large;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        section #enroll-container table td {\r\n");
      out.write("            padding: 0 10px;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <!-- Page loading scripts-->\r\n");
      out.write("    <script>\r\n");
      out.write("        (function() {\r\n");
      out.write("            window.onload = function() {\r\n");
      out.write("                var preloader = document.querySelector('.page-loading');\r\n");
      out.write("                preloader.classList.remove('active');\r\n");
      out.write("                setTimeout(function() {\r\n");
      out.write("                    preloader.remove();\r\n");
      out.write("                }, 2000);\r\n");
      out.write("            };\r\n");
      out.write("        })();\r\n");
      out.write("    </script>\r\n");
      out.write("    <!-- Vendor Styles-->\r\n");
      out.write("    <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.print(path );
      out.write("/vendor/simplebar/dist/simplebar.min.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.print(path );
      out.write("/vendor/tiny-slider/dist/tiny-slider.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.print(path );
      out.write("/vendor/flatpickr/dist/flatpickr.min.css\" />\r\n");
      out.write("    <!-- Main Theme Styles + Bootstrap-->\r\n");
      out.write("    <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.print(path );
      out.write("/css/theme.min.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- =======================around 끝=======================-->\r\n");
      out.write("\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(path );
      out.write("/style.css\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <title>cultureshock</title>\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/b4c02836de.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.print(path );
      out.write("/dist/vendor/flatpickr/dist/flatpickr.min.css\" />\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/b4c02836de.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <!-- <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor\" crossorigin=\"anonymous\"> -->\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <!-- 나의 js 코드 -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("     <script>\r\n");
      out.write("        function reserveZoneOn() {\r\n");
      out.write("            $('#reserveZone').css('display', 'block').addClass('.show');\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // function completeSelect() {\r\n");
      out.write("\r\n");
      out.write("        // }\r\n");
      out.write("\r\n");
      out.write("        function openImage() {\r\n");
      out.write("            window.open('https://www.kopis.or.kr/upload/pfmIntroImage/PF_PF194394_220711_0123230.jpg', 'detail', 'width=500px, height=500px')\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"page-loading active\">\r\n");
      out.write("        <div class=\"page-loading-inner\">\r\n");
      out.write("            <div class=\"page-spinner\"></div><span>Loading...</span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ==============헤더시작=============== -->\r\n");
      out.write("    <header>\r\n");
      out.write("        <nav class=\"navbar_custom\">\r\n");
      out.write("            <div class=\"navbar_logo_custom\" style=\"margin-left: 150px; padding: bottom 80px;\">\r\n");
      out.write("                <a href=\"");
      out.print(path );
      out.write("/main2\"> \r\n");
      out.write("                    <img src=\"logo_ver3.svg\" class=\"navbar-brand-logo_custom\" style=\"width:120px; height:120px;\">\r\n");
      out.write("                </a>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <nav class=\"navbar_menu_custom\" style=\"margin-bottom:-60px; \">\r\n");
      out.write("                <ul class=\"navbar_menu_custom\">\r\n");
      out.write("                    <li class=\"nav-item \"><a href=\"");
      out.print(path );
      out.write("/main2\">홈</a></li> \r\n");
      out.write("                    <li class=\"nav-item \"><a href=\"");
      out.print(path );
      out.write("/musical\">뮤지컬</a></li> \r\n");
      out.write("                    <li class=\"nav-item\"><a href=\"");
      out.print(path );
      out.write("/drama\">연극</a></li>\r\n");
      out.write("                    <li class=\"nav-item \"><a href=\"");
      out.print(path );
      out.write("/classic\">클래식</a></li>\r\n");
      out.write("                    <li class=\"nav-item \"><a href=\"");
      out.print(path );
      out.write("/korean\">국악</a></li>\r\n");
      out.write("                    <li class=\"nav-item dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle\" role=\"button\" id=\"board\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">게시판</a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\" aria-labelledby=\"board\">\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"");
      out.print(path );
      out.write("/notice_list\">공지게시판</a></li> \r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"");
      out.print(path );
      out.write("/review_list\">리뷰게시판</a></li> \r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"");
      out.print(path );
      out.write("/QnA_list\">문의게시판</a></li> \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"navbar_icons_custom \" style=\"margin-top:-60px;\">\r\n");
      out.write("            \t");
 if(loginMember != null){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"h5 mt-2\">");
      out.print(loginMember.getUser_name() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t님 반갑습니다\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t");
} else { 
      out.write("\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <a href=\"");
      out.print(path );
      out.write("/login\">\r\n");
      out.write("\t                        <i class=\"fa-solid fa-user\"></i>\r\n");
      out.write("\t                    </a>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <a href=\"");
      out.print(path );
      out.write("/enroll\">\r\n");
      out.write("\t                        <i class=\"fa-solid fa-user-plus\"></i>\r\n");
      out.write("\t                    </a>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t            ");
} 
      out.write("\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"dropdown-toggle\" role=\"button\" id=\"myPage\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">마이페이지</a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\" aria-labelledby=\"myPage\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print(path );
      out.write("/myPage\">마이페이지 메인</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print(path );
      out.write("/Memberupdate\">회원정보수정</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print(path );
      out.write("/bookCompleteList\">예매내역</a></li>\r\n");
      out.write("                        ");
 if(loginMember != null){ 
      out.write("\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.print(path );
      out.write("/logout\">로그아웃</a></li>\r\n");
      out.write("                        ");
} 
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- ===================헤더끝=====================-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <body>");
      out.write('\r');
      out.write('\n');


		SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
		String today = sdf.format(new Date());
		int count = 1;

		List<ShowDetail> musicalRankList = null;
		List<ShowDetail> classicRankList = null;
		List<ShowDetail> DramaRankList = null;
		List<ShowDetail> triditionalRankList = null;
		List<ShowDetail> muListAll = (List<ShowDetail>)request.getAttribute("muListAll");                 
		List<ShowDetail> koListAll = (List<ShowDetail>)request.getAttribute("koListAll");                 
		List<ShowDetail> clListAll = (List<ShowDetail>)request.getAttribute("clListAll");                 
		List<ShowRank> rankSeoul = null;
		List<ShowRank> rankKuyngki = null;
		List<ShowRank> rankKuyngsang = null;
		List<ShowRank> rankJeolla= null;
		                                
		List<Review> reviewList = null;
		                                
		List<Notice> noticeList = null;
		                                
		List<Qna> qnaList = null;
		
		if(request.getAttribute("musicalRankList")!=null){
			musicalRankList = (List<ShowDetail>)request.getAttribute("musicalRankList");
		}
		if(request.getAttribute("classicRankList")!=null){
			classicRankList = (List<ShowDetail>)request.getAttribute("classicRankList");
		}
		if(request.getAttribute("DramaRankList")!=null){
			DramaRankList = (List<ShowDetail>)request.getAttribute("DramaRankList");
		}
		if(request.getAttribute("triditionalRankList")!=null){
			triditionalRankList = (List<ShowDetail>)request.getAttribute("triditionalRankList");
		}
		if(request.getAttribute("rankSeoul")!=null){
			rankSeoul = (List<ShowRank>)request.getAttribute("rankSeoul");
		}
		if(request.getAttribute("rankKuyngki")!=null){
			rankKuyngki = (List<ShowRank>)request.getAttribute("rankKuyngki");
		}
		if(request.getAttribute("rankKuyngsang")!=null){
			rankKuyngsang = (List<ShowRank>)request.getAttribute("rankKuyngsang");
		}
		if(request.getAttribute("rankJeolla")!=null){
			rankJeolla = (List<ShowRank>)request.getAttribute("rankJeolla");
		}
		if(request.getAttribute("reviewList")!=null){
			reviewList = (List<Review>)request.getAttribute("reviewList");
		}
		if(request.getAttribute("noticeList")!=null){
			noticeList = (List<Notice>)request.getAttribute("noticeList");
		}
		if(request.getAttribute("qnaList")!=null){
			qnaList = (List<Qna>)request.getAttribute("qnaList");
		}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("  <!-- 슬라이드 시작 -->\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("        <!-- Hero - Featured Products (tabs)-->\r\n");
      out.write("        <section  style=\"background-color: #9A161F; padding-bottom:10px;\">\r\n");
      out.write("            <div class=\"shape shape-bottom shape-curve \" >\r\n");
      out.write("                <svg  xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 3000 185.4\">\r\n");
      out.write("          </svg>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 검색창 시작 -->\r\n");
      out.write(" \t\t\t<div class=\"container \" style=\"padding-left:55px; padding-top:40px; padding-bottom:40px;\">\r\n");
      out.write("                <div class=\"row justify-content-center \">\r\n");
      out.write("                    <div class=\"col-lg-7 \">\r\n");
      out.write("                        <form class=\"input-group\" action=\"");
      out.print(path);
      out.write("/searchFromMain\">\r\n");
      out.write("                            <input  class=\"form-control\" type=\"text\" name=\"searchWord\" required>\r\n");
      out.write("                            <button class=\"btn btn-primary-3 \" type=\"submit\"><i class=\"ai-search fs-xl-1 me-1\"></i></button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 검색창 끝 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- Categories (carousel)-->\r\n");
      out.write("            <section class=\"container position-relative zindex-5\" >\r\n");
      out.write("                <div class=\"tns-carousel-wrapper container\" style=\"margin-bottom:10px;\">\r\n");
      out.write("                    <div class=\"tns-carousel-inner\"  data-carousel-options=\"{&quot;items&quot;: 3, &quot;controls&quot;: false, &quot;gutter&quot;: 24, &quot;responsive&quot;: {&quot;0&quot;:{&quot;items&quot;:1},&quot;560&quot;:{&quot;items&quot;:2},&quot;850&quot;:{&quot;items&quot;:3}}}\">\r\n");
      out.write("                       \r\n");
      out.write("                       \r\n");
      out.write("                      \t\t<div class=\"col-4\" style=\"margin-left:70px;\">\r\n");
      out.write("\t                                <img style=\"width:280px; height:380px;\" src=\"");
      out.print(classicRankList.get(0).getPoster() );
      out.write("\" alt=\"지킬엔하이드\">\r\n");
      out.write("\t                               <div style=\"display: inline-block; margin-left: 20px\">\r\n");
      out.write("\t\t                                <div style=\"margin-top:10px; margin-left:-15px; font-size: 1.7em; font: bold;  color:  white;\">(클래식)");
      out.print(classicRankList.get(0).getPrfnm() );
      out.write(" </div>\r\n");
      out.write("\t\t                                 <div style=\"margin-top:10px; margin-left:-15px; font-size: 1.5em;   color:  white; \">2022.08.08(월)~08.29(월) </div>\r\n");
      out.write("\t\t                                    <button style=\"margin-top:10px; margin-left:20px;\" type=\"button\" class=\"btn btn-outline-light button-2\"><a href=\"");
      out.print(path );
      out.write("/showSelect?prfid=");
      out.print(classicRankList.get(0).getPrfid());
      out.write("\">자세히보기</a></button>\r\n");
      out.write("\t                                        </div>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                                          \t\t \r\n");
      out.write("                                   <div class=\"col-4\" >\r\n");
      out.write("\t                                                <img style=\"width:280px; height:380px;\" src=\"");
      out.print(classicRankList.get(2).getPoster() );
      out.write("\" alt=\"지킬엔하이드\">\r\n");
      out.write("\t                                                <div style=\"display: inline-block; margin-left: 20px\">\r\n");
      out.write("\t\t                                                <div style=\"margin-top:10px;  margin-left:-5px; font-size: 1.7em; font: bold;  color:  white;\">(클래식)");
      out.print(classicRankList.get(2).getPrfnm() );
      out.write(" </div>\r\n");
      out.write("\t\t                                                <div style=\"margin-top:10px; margin-left:-10px; font-size: 1.5em;   color:  white; \">2022.07.31(일)~09.01(목) </div>\r\n");
      out.write("\t\t                                                <button style=\"margin-top:10px; margin-left:20px; \" type=\"button\" class=\"btn btn-outline-light button-2\"><a href=\"");
      out.print(path );
      out.write("/showSelect?prfid=");
      out.print(classicRankList.get(2).getPrfid());
      out.write("\">자세히보기</a></button>\r\n");
      out.write("\t                                                </div>\r\n");
      out.write("                                          \t\t </div>    \r\n");
      out.write("                                          \t\t   \r\n");
      out.write("                                   <div class=\"col-4\">\r\n");
      out.write("\t                                                <img style=\"width:280px; height:380px;\" src=\"");
      out.print(clListAll.get(3).getPoster() );
      out.write("\" alt=\"지킬엔하이드\">\r\n");
      out.write("\t                                                <div style=\"display: inline-block; margin-left: 20px\">\r\n");
      out.write("\t\t                                                <div style=\"margin-top:10px; margin-left:-10px; font-size: 1.7em; font: bold;  color:  white;\">(클래식)");
      out.print(clListAll.get(3).getPrfnm() );
      out.write(" </div>\r\n");
      out.write("\t\t                                                <div style=\"margin-top:10px; margin-left:-10px; font-size: 1.5em;   color:  white; \">2022.07.31(일)~09.14(수) </div>\r\n");
      out.write("\t\t                                                <button style=\"margin-top:10px; margin-left:20px; \" type=\"button\" class=\"btn btn-outline-light button-2\"><a href=\"");
      out.print(path );
      out.write("/showSelect?prfid=");
      out.print(clListAll.get(3).getPrfid());
      out.write("\">자세히보기</a></button>\r\n");
      out.write("\t                                                </div>\r\n");
      out.write("                                          \t\t </div>      \r\n");
      out.write("          \r\n");
      out.write("         \t\t\t\t\t\t\t\t\t  <div class=\"col-4\">\r\n");
      out.write("\t                                                <img style=\"width:280px; height:380px;\" src=\"");
      out.print(musicalRankList.get(0).getPoster() );
      out.write("\" alt=\"지킬엔하이드\">\r\n");
      out.write("\t                                                <div style=\"display: inline-block; margin-left: 20px\">\r\n");
      out.write("\t\t                                                <div style=\"margin-top:10px; margin-left:30px; font-size: 1.7em; font: bold;  color:  white;\">(뮤지컬)");
      out.print(musicalRankList.get(0).getPrfnm() );
      out.write(" </div>\r\n");
      out.write("\t\t                                                <div style=\"margin-top:10px; margin-left:-10px; font-size: 1.5em;   color:  white; \">2022.07.01(금)~08.31(수) </div>\r\n");
      out.write("\t\t                                                <button style=\"margin-top:10px; margin-left:20px; \" type=\"button\" class=\"btn btn-outline-light button-2\"><a href=\"");
      out.print(path );
      out.write("/showSelect?prfid=");
      out.print(musicalRankList.get(0).getPrfid());
      out.write("\">자세히보기</a></button>\r\n");
      out.write("\t                                                </div>\r\n");
      out.write("                                          \t\t </div>\r\n");
      out.write("\t\r\n");
      out.write("\t                                              <div class=\"col-4\" >\r\n");
      out.write("\t                                                <img style=\"width:280px; height:380px;\" src=\"");
      out.print(musicalRankList.get(2).getPoster() );
      out.write("\" alt=\"지킬엔하이드\">\r\n");
      out.write("\t                                                <div style=\"display: inline-block; margin-left: 20px\">\r\n");
      out.write("\t\t                                                <div style=\"margin-top:10px;  margin-left:30px; font-size: 1.7em; font: bold;  color:  white;\">(뮤지컬)");
      out.print(musicalRankList.get(2).getPrfnm() );
      out.write(" </div>\r\n");
      out.write("\t\t                                                <div style=\"margin-top:10px; margin-left:-10px; font-size: 1.5em;   color:  white; \">2022.08.01(월)~09.20(화) </div>\r\n");
      out.write("\t\t                                                <button style=\"margin-top:10px; margin-left:20px; \" type=\"button\" class=\"btn btn-outline-light button-2\"><a href=\"");
      out.print(path );
      out.write("/showSelect?prfid=");
      out.print(musicalRankList.get(2).getPrfid());
      out.write("\">자세히보기</a></button>\r\n");
      out.write("\t                                                </div>\r\n");
      out.write("                                          \t\t </div> \r\n");
      out.write("                                          \t\t \r\n");
      out.write("\t                                              <div class=\"col-4\" >\r\n");
      out.write("\t                                                <img style=\"width:280px; height:380px;\" src=\"");
      out.print(musicalRankList.get(3).getPoster() );
      out.write("\" alt=\"지킬엔하이드\">\r\n");
      out.write("\t                                                <div style=\"display: inline-block; margin-left: 20px\">\r\n");
      out.write("\t\t                                                <div style=\"margin-top:10px; margin-left:10px; font-size: 1.7em; font: bold;  color:  white;\">(뮤지컬)");
      out.print(musicalRankList.get(3).getPrfnm() );
      out.write(" </div>\r\n");
      out.write("\t\t                                                <div style=\"margin-top:10px; margin-left:-10px; font-size: 1.5em;   color:  white; \">2022.08.01(월)~09.03(토) </div>\r\n");
      out.write("\t\t                                                <button style=\"margin-top:10px; margin-left:20px; \" type=\"button\" class=\"btn btn-outline-light button-2\"><a href=\"");
      out.print(path );
      out.write("/showSelect?prfid=");
      out.print(musicalRankList.get(3).getPrfid());
      out.write("\">자세히보기</a></button>\r\n");
      out.write("\t                                                </div>\r\n");
      out.write("                                          \t\t </div> \r\n");
      out.write("                        \r\n");
      out.write("                       \t\t\t\t\t\t\t  <div class=\"col-4\">\r\n");
      out.write("\t                                                <img style=\"width:280px; height:380px;\" src=\"");
      out.print(DramaRankList.get(0).getPoster() );
      out.write("\" alt=\"지킬엔하이드\">\r\n");
      out.write("\t                                                <div style=\"display: inline-block; margin-left: 20px\">\r\n");
      out.write("\t\t                                                <div style=\"margin-top:10px; margin-left:65px; font-size: 1.7em; font: bold;  color:  white;\">(연극)");
      out.print(DramaRankList.get(0).getPrfnm() );
      out.write(" </div>\r\n");
      out.write("\t\t                                                <div style=\"margin-top:10px; margin-left:-10px; font-size: 1.5em;   color:  white; \">2022.08.20(토)~09.14(수) </div>\r\n");
      out.write("\t\t                                                <button style=\"margin-top:10px; margin-left:20px; \" type=\"button\" class=\"btn btn-outline-light button-2\"><a href=\"");
      out.print(path );
      out.write("/showSelect?prfid=");
      out.print(DramaRankList.get(0).getPrfid());
      out.write("\">자세히보기</a></button>\r\n");
      out.write("\t                                                </div>\r\n");
      out.write("                                          \t\t </div>\r\n");
      out.write("\t\r\n");
      out.write("\t                                              <div class=\"col-4\" >\r\n");
      out.write("\t                                                <img style=\"width:280px; height:380px;\" src=\"");
      out.print(DramaRankList.get(2).getPoster() );
      out.write("\" alt=\"지킬엔하이드\">\r\n");
      out.write("\t                                                <div style=\"display: inline-block; margin-left: 20px\">\r\n");
      out.write("\t\t                                                <div style=\"margin-top:10px; margin-left:50px; font-size: 1.7em; font: bold;  color:  white;\">(연극)");
      out.print(DramaRankList.get(2).getPrfnm() );
      out.write(" </div>\r\n");
      out.write("\t\t                                                <div style=\"margin-top:10px; margin-left:-10px; font-size: 1.5em;   color:  white; \">2022.08.17(수)~09.30(금) </div>\r\n");
      out.write("\t\t                                                <button style=\"margin-top:10px; margin-left:20px; \" type=\"button\" class=\"btn btn-outline-light button-2\"><a href=\"");
      out.print(path );
      out.write("/showSelect?prfid=");
      out.print(DramaRankList.get(2).getPrfid());
      out.write("\">자세히보기</a></button>\r\n");
      out.write("\t                                                </div>\r\n");
      out.write("                                          \t\t </div>   \r\n");
      out.write("                                          \t\t  \r\n");
      out.write("\t                                              <div class=\"col-4\" >\r\n");
      out.write("\t                                                <img style=\"width:280px; height:380px;\" src=\"");
      out.print(DramaRankList.get(3).getPoster() );
      out.write("\" alt=\"지킬엔하이드\">\r\n");
      out.write("\t                                                <div style=\"display: inline-block; margin-left: 20px\">\r\n");
      out.write("\t\t                                                <div style=\"margin-top:10px; margin-left:-22px; font-size: 1.7em; font: bold;  color:  white;\">(연극)");
      out.print(DramaRankList.get(3).getPrfnm() );
      out.write(" </div>\r\n");
      out.write("\t\t                                                <div style=\"margin-top:10px; margin-left:-10px; font-size: 1.5em;   color:  white; \">2022.08.17(수)~09.30(금) </div>\r\n");
      out.write("\t\t                                                <button style=\"margin-top:10px; margin-left:20px; \" type=\"button\" class=\"btn btn-outline-light button-2\"><a href=\"");
      out.print(path );
      out.write("/showSelect?prfid=");
      out.print(DramaRankList.get(3).getPrfid());
      out.write("\">자세히보기</a></button>\r\n");
      out.write("\t                                                </div>\r\n");
      out.write("                                          \t\t </div> \r\n");
      out.write("                                          \t\t    \r\n");
      out.write("\t                                              <div class=\"col-4\" >\r\n");
      out.write("\t                                                <img style=\"width:280px; height:380px;\" src=\"");
      out.print(koListAll.get(0).getPoster() );
      out.write("\" alt=\"지킬엔하이드\">\r\n");
      out.write("\t                                                <div style=\"display: inline-block; margin-left: 20px\">\r\n");
      out.write("\t\t                                                <div style=\"margin-top:10px; margin-left:8px; font-size: 1.7em; font: bold;  color:  white;\">(국악)");
      out.print(koListAll.get(0).getPrfnm() );
      out.write(" </div>\r\n");
      out.write("\t\t                                                <div style=\"margin-top:10px; margin-left:-10px; font-size: 1.5em;   color:  white; \">2022.08.17(수)~08.28(일) </div>\r\n");
      out.write("\t\t                                                <button style=\"margin-top:10px; margin-left:20px; \" type=\"button\" class=\"btn btn-outline-light button-2\"><a href=\"");
      out.print(path );
      out.write("/showSelect?prfid=");
      out.print(koListAll.get(0).getPrfid());
      out.write("\">자세히보기</a></button>\r\n");
      out.write("\t                                                </div>\r\n");
      out.write("                                          \t\t </div>    \r\n");
      out.write("                                          \t\t \r\n");
      out.write("\t                                              <div class=\"col-4\" >\r\n");
      out.write("\t                                                <img style=\"width:280px; height:380px;\" src=\"");
      out.print(koListAll.get(1).getPoster() );
      out.write("\" alt=\"지킬엔하이드\">\r\n");
      out.write("\t                                                <div style=\"display: inline-block; margin-left: 20px\">\r\n");
      out.write("\t\t                                                <div style=\"margin-top:10px; margin-left:-55px; font-size: 1.7em; font: bold;  color:  white;\">(국악)");
      out.print(koListAll.get(1).getPrfnm() );
      out.write(" </div>\r\n");
      out.write("\t\t                                                <div style=\"margin-top:10px; margin-left:-10px; font-size: 1.5em;   color:  white; \">2022.08.17(수)~09.30(금) </div>\r\n");
      out.write("\t\t                                                <button style=\"margin-top:10px; margin-left:20px; \" type=\"button\" class=\"btn btn-outline-light button-2\"><a href=\"");
      out.print(path );
      out.write("/showSelect?prfid=");
      out.print(koListAll.get(1).getPrfid());
      out.write("\">자세히보기</a></button>\r\n");
      out.write("\t                                                </div>\r\n");
      out.write("                                          \t\t </div>    \r\n");
      out.write("                                          \t\t \r\n");
      out.write("\t                                              <div class=\"col-4\" >\r\n");
      out.write("\t                                                <img style=\"width:280px; height:380px;\" src=\"");
      out.print(koListAll.get(8).getPoster() );
      out.write("\" alt=\"지킬엔하이드\">\r\n");
      out.write("\t                                                <div style=\"display: inline-block; margin-left: 20px\">\r\n");
      out.write("\t\t                                                <div style=\"margin-top:10px; margin-left:15px; font-size: 1.7em; font: bold;  color:  white;\">(국악)");
      out.print(koListAll.get(8).getPrfnm() );
      out.write(" </div>\r\n");
      out.write("\t\t                                                <div style=\"margin-top:10px; margin-left:-10px; font-size: 1.5em;   color:  white; \">2022.08.17(수)~10.13(목) </div>\r\n");
      out.write("\t\t                                                <button style=\"margin-top:10px; margin-left:20px; \" type=\"button\" class=\"btn btn-outline-light button-2\"><a href=\"");
      out.print(path );
      out.write("/showSelect?prfid=");
      out.print(koListAll.get(8).getPrfid());
      out.write("\">자세히보기</a></button>\r\n");
      out.write("\t                                                </div>\r\n");
      out.write("                                          \t\t </div>    \r\n");
      out.write("                                          \t\t \r\n");
      out.write("                                          \t\t\r\n");
      out.write("           \r\n");
      out.write("          \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("        </section>\r\n");
      out.write("  \r\n");
      out.write("   \r\n");
      out.write("        <!-- 슬라이드 끝 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- 랭킹시작-->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container p-7\" style=\"margin-top:-30px;\">\r\n");
      out.write("            <div  style=\"margit-left:-650px; margin-bottom:-80px;\">\r\n");
      out.write("                <p class=\"h1 mb-5 fs-1 \" style=\" color: #9A161F; \">Ranking</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"masonry-filterable\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- Filters -->\r\n");
      out.write("                <ul class=\"masonry-filters nav nav-tabs justify-content-center pb-4\" style=\"color:#9A161F;\">\r\n");
      out.write("                   \r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link active\" href=\"#\" data-group=\"musical\" style=\"color:#9A161F; font-size:20px;\">뮤지컬</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"#\" data-group=\"theater\" style=\"color:#9A161F; font-size:20px;\">연극</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"#\" data-group=\"classic\" style=\"color:#9A161F; font-size:20px;\">클래식</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"#\" data-group=\"korean\" style=\"color:#9A161F; font-size:20px;\">국악</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("\r\n");
      out.write("                <!-- Grid -->\r\n");
      out.write("                <div class=\"masonry-grid\" data-columns=\"4\">\r\n");
      out.write("\t\t\t\t\t");

						if(musicalRankList!=null && musicalRankList.size()>0){
							for(int i = 0; i < 4;i++){
							String marginCount = "";
					
      out.write("\r\n");
      out.write("                    <!-- Item -->\r\n");
      out.write("                    <div class=\"masonry-grid-item\" data-groups='[\"musical\"]' >\r\n");
      out.write("\r\n");
      out.write("                        <!-- Image on top -->\r\n");
      out.write("                  \t\t");

                  			if(i==0){
                  				marginCount  = "";
                  			}else{
                  				marginCount = i +"";
                  			}
                  		
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"card cardSize mar");
      out.print(marginCount);
      out.write("\">\r\n");
      out.write("                            <img src=\"");
      out.print(path );
      out.write("/resources/caliburn_");
      out.print(count++ );
      out.write(".svg\" class=\"card-img-top imgSize\" alt=\"Card image\"style=\"height:200px;\">\r\n");
      out.write("                            <div class=\"card-body\"style=\"height:270px;\">\r\n");
      out.write("                                <h5 class=\"card-title\">");
      out.print(musicalRankList.get(i).getPrfnm() );
      out.write("</h5>\r\n");
      out.write("                                <p class=\"card-text fs-sm\">공연장:");
      out.print(musicalRankList.get(i).getFcltynm());
      out.write(" <br> 가격:");
      out.print(musicalRankList.get(i).getPcseguidance() );
      out.write(" <br>관람연령: ");
      out.print(musicalRankList.get(i).getPrfage());
      out.write("<br>기간: ");
      out.print(musicalRankList.get(i).getPrfpdfrom());
      out.write('-');
      out.print(musicalRankList.get(i).getPrfpdto() );
      out.write("</p>\r\n");
      out.write("                                <a href=\"");
      out.print(path );
      out.write("/detailFromMain?prfmid=");
      out.print(musicalRankList.get(i).getPrfid() );
      out.write("\" class=\"btn btn-sm btn-primary\" style=\"background-color: #9A161F; border: #9A161F;\">더보기</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("            \t\t");

            				
            		
							} 
						}
            		
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    ");

						if(DramaRankList!=null && DramaRankList.size()>0){
							for(int i = 0; i < 4;i++){
							String marginCount = "";
					
      out.write("\r\n");
      out.write("                    <!-- Item -->\r\n");
      out.write("                    <div class=\"masonry-grid-item\" data-groups='[\"theater\"]'>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Image on top -->\r\n");
      out.write("                  \t\t");

                  			if(i==0){
                  				marginCount  = "";
                  			}else{
                  				marginCount = i +"";
                  			}
                  		
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"card cardSize mar");
      out.print(marginCount);
      out.write("\">\r\n");
      out.write("                            <img src=\"");
      out.print(path );
      out.write("/resources/caliburn_");
      out.print(count++ );
      out.write(".svg\" class=\"card-img-top imgSize\" alt=\"Card image\" style=\"height:200px;\">\r\n");
      out.write("                            <div class=\"card-body\"style=\"height:270px;\">\r\n");
      out.write("                                <h5 class=\"card-title\">");
      out.print(DramaRankList.get(i).getPrfnm() );
      out.write("</h5>\r\n");
      out.write("                                <p class=\"card-text fs-sm\">공연장:");
      out.print(DramaRankList.get(i).getFcltynm());
      out.write(" \r\n");
      out.write("                                <br> 가격:");
      out.print(DramaRankList.get(i).getPrfpdto() );
      out.write(" \r\n");
      out.write("                                <br>관람연령: ");
      out.print(DramaRankList.get(i).getPrfage());
      out.write("\r\n");
      out.write("                                <br>기간: ");
      out.print(DramaRankList.get(i).getPrfpdfrom());
      out.write('-');
      out.print(DramaRankList.get(i).getPrfpdfrom());
      out.write("</p>\r\n");
      out.write("                                <a href=\"");
      out.print(path );
      out.write("/detailFromMain?prfmid=");
      out.print(DramaRankList.get(i).getPrfid() );
      out.write("\" class=\"btn btn-sm btn-primary\" style=\"background-color: #9A161F; border: #9A161F;\">더보기</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("            \t\t");

            				
							} 
						}
            		
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("                    ");

						if(classicRankList!=null && classicRankList.size()>0){
							for(int i = 0; i < 4;i++){
							String marginCount = "";
					
      out.write("\r\n");
      out.write("                    <!-- Item -->\r\n");
      out.write("                    <div class=\"masonry-grid-item\" data-groups='[\"classic\"]'>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Image on top -->\r\n");
      out.write("                  \t\t");

                  			if(i==0){
                  				marginCount  = "";
                  			}else{
                  				marginCount = i +"";
                  			}
                  		
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"card cardSize mar");
      out.print(marginCount);
      out.write("\">\r\n");
      out.write("                            <img src=\"");
      out.print(path );
      out.write("/resources/caliburn_");
      out.print( count++ );
      out.write(".svg\" class=\"card-img-top imgSize\" alt=\"Card image\"style=\"height:200px;\">\r\n");
      out.write("                            <div class=\"card-body\"style=\"height:270px;\">\r\n");
      out.write("                                <h5 class=\"card-title\">");
      out.print(classicRankList.get(i).getPrfnm() );
      out.write("</h5>\r\n");
      out.write("                                <p class=\"card-text fs-sm\">공연장:");
      out.print(classicRankList.get(i).getFcltynm());
      out.write(" \r\n");
      out.write("                                <br> 가격:");
      out.print(classicRankList.get(i).getPrfpdto() );
      out.write(" \r\n");
      out.write("                                <br>관람연령: ");
      out.print(classicRankList.get(i).getPrfage());
      out.write("\r\n");
      out.write("                                <br>기간: ");
      out.print(classicRankList.get(i).getPrfpdfrom());
      out.write('-');
      out.print(classicRankList.get(i).getPrfpdfrom());
      out.write("</p>\r\n");
      out.write("                                <a href=\"");
      out.print(path );
      out.write("/detailFromMain?prfmid=");
      out.print(classicRankList.get(i).getPrfid() );
      out.write("\" class=\"btn btn-sm btn-primary\" style=\"background-color: #9A161F; border: #9A161F;\">더보기</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("            \t\t");

            				
							} 
						}
            		
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    ");

						if(triditionalRankList!=null && triditionalRankList.size()>0){
							for(int i = 0; i < 4;i++){
							String marginCount = "";
					
      out.write("\r\n");
      out.write("                    <!-- Item -->\r\n");
      out.write("                    <div class=\"masonry-grid-item\" data-groups='[\"korean\"]'>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Image on top -->\r\n");
      out.write("                  \t\t");

                  			if(i==0){
                  				marginCount  = "";
                  			}else{
                  				marginCount = i +"";
                  			}
                  		
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"card cardSize mar");
      out.print(marginCount);
      out.write("\">\r\n");
      out.write("                            <img src=\"");
      out.print(path );
      out.write("/resources/caliburn_");
      out.print(count++ -1 );
      out.write(".svg\" class=\"card-img-top imgSize\" alt=\"Card image\"style=\"height:200px;\">\r\n");
      out.write("                            <div class=\"card-body\"style=\"height:270px;\">\r\n");
      out.write("                                 <h5 class=\"card-title\">");
      out.print(triditionalRankList.get(i).getPrfnm() );
      out.write("</h5>\r\n");
      out.write("                                <p class=\"card-text fs-sm\">공연장:");
      out.print(triditionalRankList.get(i).getFcltynm());
      out.write(" \r\n");
      out.write("                                <br> 가격:");
      out.print(triditionalRankList.get(i).getPrfpdto() );
      out.write(" \r\n");
      out.write("                                <br>관람연령: ");
      out.print(triditionalRankList.get(i).getPrfage());
      out.write("\r\n");
      out.write("                                <br>기간: ");
      out.print(triditionalRankList.get(i).getPrfpdfrom());
      out.write('-');
      out.print(triditionalRankList.get(i).getPrfpdfrom());
      out.write("</p>\r\n");
      out.write("                                <a href=\"");
      out.print(path );
      out.write("/detailFromMain?prfmid=");
      out.print(triditionalRankList.get(i).getPrfid() );
      out.write("\" class=\"btn btn-sm btn-primary\" style=\"background-color: #9A161F; border: #9A161F;\">더보기</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("            \t\t");

            				
							} 
						}
            		
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- More items... -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 랭킹 끝-->\r\n");
      out.write("\r\n");
      out.write("        <!-- 지역별 랭킹 시작 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div style=\"margin-top:-100px;\">\r\n");
      out.write("            <div class=\"container mt-5 p-10\">\r\n");
      out.write("                <p class=\"h1 mb-4 fs-1 \" style=\"padding-bottom: -4; margin-left: 230px; color: #9A161F;\">Regional ranking</p>\r\n");
      out.write("                <div class=\"d-flex align-items-start\">\r\n");
      out.write("                    <div class=\"nav flex-column nav-pills  me-3\" id=\"v-pills-tab\" role=\"tablist\" aria-orientation=\"vertical\">\r\n");
      out.write("                        <button class=\"nav-link active\" id=\"v-pills-home-tab\" data-bs-toggle=\"pill\" data-bs-target=\"#v-pills-home\" type=\"button\" role=\"tab\" aria-controls=\"v-pills-home\" aria-selected=\"true\">서울</button>\r\n");
      out.write("                        <button class=\"nav-link \" id=\"v-pills-profile-tab\" data-bs-toggle=\"pill\" data-bs-target=\"#gyeonggi\" type=\"button\" role=\"tab\" aria-controls=\"v-pills-profile\" aria-selected=\"false\">경기</button>\r\n");
      out.write("                        <button class=\"nav-link \" id=\"v-pills-messages-tab\" data-bs-toggle=\"pill\" data-bs-target=\"#v-pills-messages\" type=\"button\" role=\"tab\" aria-controls=\"v-pills-messages\" aria-selected=\"false\">대구/부산/경북/경남</button>\r\n");
      out.write("                        <button class=\"nav-link \" id=\"v-pills-settings-tab\" data-bs-toggle=\"pill\" data-bs-target=\"#v-pills-settings\" type=\"button\" role=\"tab\" aria-controls=\"v-pills-settings\" aria-selected=\"false\">대전/전라/전남/전북</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"tab-content\" id=\"v-pills-tabContent\">\r\n");
      out.write("                        <div class=\"tab-pane fade show active tabSize\" id=\"v-pills-home\" role=\"tabpanel\" aria-labelledby=\"seoul\">\r\n");
      out.write("                            \r\n");
      out.write("                            ");
if(rankSeoul!=null &&rankSeoul.size()>0) {
                            	int num = 1;
                            	for(int i = 0; i<4;i++){
                            
      out.write("\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"card-1 cardSize-");
      out.print(num);
      out.write("\">\r\n");
      out.write("                            \t<a href=\"");
      out.print(path);
      out.write("/detailFromMain?prfmid=");
      out.print(rankSeoul.get(i).getPrfid() );
      out.write(" \">\r\n");
      out.write("                                <img src=\"");
      out.print(rankSeoul.get(i).getPoster() );
      out.write("\" class=\"imgSize-1 \" alt=\"Card image\">\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"card-body text-center\">\r\n");
      out.write("                                    <h6 class=\"card-title mar-top\" style=\"width:; margin-left:0px;\">");
      out.print(rankSeoul.get(i).getPrfnm() );
      out.write("</h6>\r\n");
      out.write("                                    <p class=\"card-text fs-sm mar-top\"style=\"width:; margin-left:0px;\">");
      out.print(today );
      out.write(" </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            ");
		
                            
                            		num ++;
                            		if(num > 2 ){
                            			num = 1;
                            		}
                            		if(rankSeoul.size()==i){
                            			break;
                            		}
                            
      out.write("\r\n");
      out.write("                            ");
		}
                            	}
                            
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"tab-pane fade tabSize\" id=\"gyeonggi\" role=\"tabpanel\" aria-labelledby=\"v-pills-profile-tab\">\r\n");
      out.write("                            ");
if(rankKuyngki!=null &&rankKuyngki.size()>0) {
                            	int num = 1;
                            	for(int i = 0; i<4;i++){
                            
      out.write("\r\n");
      out.write("                            <div class=\"card-1 cardSize-");
      out.print(num);
      out.write("\">\r\n");
      out.write("                            \t<a href=\"");
      out.print(path);
      out.write("/detailFromMain?prfmid=");
      out.print(rankKuyngki.get(i).getPrfid());
      out.write("\">\r\n");
      out.write("                                <img src=\"");
      out.print(rankKuyngki.get(i).getPoster() );
      out.write("\" class=\"imgSize-1 \" alt=\"Card image\">\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"card-body text-center\">\r\n");
      out.write("                                    <h6 class=\"card-title mar-top\" style=\"width:; margin-left:0px;\">");
      out.print(rankKuyngki.get(i).getPrfnm() );
      out.write("</h6>\r\n");
      out.write("                                    <p class=\"card-text fs-sm mar-top\"style=\"width:; margin-left:0px;\">");
      out.print(today );
      out.write(" </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            ");
		
                            
                            		num ++;
                            		if(num > 2 ){
                            			num = 1;
                            		}
                            		if((rankKuyngki.size()-1)==i){
                            			break;
                            		}
                            
      out.write("\r\n");
      out.write("                            ");
		}
                            	}
                            
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"tab-pane fade tabSize\" id=\"v-pills-messages\" role=\"tabpanel\" aria-labelledby=\"v-pills-messages-tab\">\r\n");
      out.write("                            ");
if(rankKuyngsang!=null &&rankKuyngsang.size()>0) {
                            	int num = 1;
                            	for(int i = 0; i<4;i++){
                            
      out.write("\r\n");
      out.write("                            <div class=\"card-1 cardSize-");
      out.print(num);
      out.write("\">\r\n");
      out.write("                                <a href=\"");
      out.print(path);
      out.write("/detailFromMain?prfmid=");
      out.print(rankKuyngsang.get(i).getPrfid());
      out.write("\">\r\n");
      out.write("                            \r\n");
      out.write("                                <img src=\"");
      out.print(rankKuyngsang.get(i).getPoster() );
      out.write("\" class=\"imgSize-1 \" alt=\"Card image\">\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"card-body text-center\">\r\n");
      out.write("                                    <h6 class=\"card-title mar-top\" style=\"width:; margin-left:0px;\">");
      out.print(rankKuyngsang.get(i).getPrfnm() );
      out.write("</h6>\r\n");
      out.write("                                    <p class=\"card-text fs-sm mar-top\"style=\"width:; margin-left:0px;\">");
      out.print(today );
      out.write(" </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            ");
		
                            
                            		num ++;
                            		if(num > 2 ){
                            			num = 1;
                            		}
                            		if((rankKuyngsang.size()-1)==i){
                            			break;
                            		}
                            
      out.write("\r\n");
      out.write("                            ");
		}
                            	}
                            
      out.write("\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"tab-pane fade tabSize\" id=\"v-pills-settings\" role=\"tabpanel\" aria-labelledby=\"v-pills-settings-tab\">\r\n");
      out.write("                        \r\n");
      out.write("                            ");
if(rankJeolla!=null &&rankJeolla.size()>0) {
                            	int num = 1;
                            	for(int i = 0; i<4;i++){
                            
      out.write("\r\n");
      out.write("                            <div class=\"card-1 cardSize-");
      out.print(num);
      out.write("\">\r\n");
      out.write("                                <a href=\"");
      out.print(path);
      out.write("/detailFromMain?prfmid=");
      out.print(rankJeolla.get(i).getPrfid());
      out.write("\">\r\n");
      out.write("                            \r\n");
      out.write("                                <img src=\"");
      out.print(rankJeolla.get(i).getPoster() );
      out.write("\" class=\"imgSize-1 \" alt=\"Card image\">\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"card-body text-center\">\r\n");
      out.write("                                    <h6 class=\"card-title mar-top\" style=\"width:; margin-left:0px;\">");
      out.print(rankJeolla.get(i).getPrfnm() );
      out.write("</h6>\r\n");
      out.write("                                    <p class=\"card-text fs-sm mar-top\"style=\"width:; margin-left:0px;\">");
      out.print(today );
      out.write(" </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            ");
		
                            		num ++;
                            		if(num > 2 ){
                            			num = 1;
                            		}
                            		if((rankJeolla.size()-1)==i){
                            			break;
                            		}
                            
      out.write("\r\n");
      out.write("                            ");
		}
                            	}
                            
      out.write("\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 지역별 랭킹 끝 -->\r\n");
      out.write("\r\n");
      out.write("        <!-- 관람 후기-->\r\n");
      out.write("        <div class=\"space-1\" style=\"width: 35%; display:inline-block; \" >\r\n");
      out.write("            <p class=\"h1 mb-4 fs-1 \" style=\" margin-left: 260px; color: #9A161F;\">Review\r\n");
      out.write("                <a href=\"");
      out.print(path);
      out.write("/review_list\">\r\n");
      out.write("                    <svg style=\" margin-left:170px;\" xmlns=\"http://www.w3.org/2000/svg\" width=\"30\" height=\"30\" fill=\"currentColor\" class=\"bi bi-plus-square\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                    <path d=\"M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z\"/>\r\n");
      out.write("                    <path d=\"M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z\"/>\r\n");
      out.write("                  </svg>\r\n");
      out.write("                </a>\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("            <!-- Events-->\r\n");
      out.write("            <div class=\"position-relative zindex-5 container\">\r\n");
      out.write("            \t");
if(reviewList != null && reviewList.size() > 0){
            		for(int i = 0 ;i<6;i++){

            	
      out.write("\r\n");
      out.write("    \t       <div class=\"tns-carousel-wrapper\">\r\n");
      out.write("            \t\r\n");
      out.write("\t               <div class=\"pb-2\">\r\n");
      out.write("\t                   <div class=\"card h-100 border-0 shadow mx-1\">\r\n");
      out.write("\t                       <div class=\"card-body py-1 px-4\" style=\"padding: bottom 3rem; \">\r\n");
      out.write("\t                           <div class=\"d-sm-flex py-sm-2 px-lg-3\">\r\n");
      out.write("\t                               <div class=\"text-sm-center mt-3 pt-2 mt-sm-n3\"><span class=\"d-sm-block text-primary me-2 me-sm-0 mb-n3 pe-2\" style=\"font-size: 1.3rem; color: #9A161F; width:7px;\"></span><span class=\"fs-xl text-muted text-uppercase text-start\"></span></div>\r\n");
      out.write("\t                               <h3 class=\"h4 nav-heading mb-4 mt-3 pe-2\"style=\" width:420px;;\"><a href=\"");
      out.print(path);
      out.write("/review_view?reviewNum=");
      out.print(reviewList.get(i).getReviewnum());
      out.write("\" style=\"font-size: 1rem;absolute:true;\">");
      out.print(reviewList.get(i).getRcontent() );
      out.write(" </a></h3>\r\n");
      out.write("\t                               <a class=\"d-flex meta-link fs-sm align-items-center pt-2 ps-2\" href=\"#\"><img class=\"rounded-circle\" src=\"");
      out.print(path );
      out.write("/resources/p_");
      out.print(i );
      out.write(".svg\" alt=\"Charlie Welch\" width=\"42\">\r\n");
      out.write("\t                                   <div class=\"ps-2 ms-1 mt-n1\"><span class=\"fw-semibold ms-1\">");
      out.print(reviewList.get(i).getUser_id() );
      out.write("</span></div>\r\n");
      out.write("\t                               </a>\r\n");
      out.write("\t                           </div>\r\n");
      out.write("\t                       </div>\r\n");
      out.write("\t                   </div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("               ");

            		}
            	}
               
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- 공지사항, 자주하는질문 시작 -->\r\n");
      out.write("        <div class=\"container mb-7  \" style=\"margin-top:120px;\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row justify-content-center\">\r\n");
      out.write("                <div class=\"col-lg-6\" style=\"margin-left:-300px\">\r\n");
      out.write("                    <div class=\"text-center p-2\" style=\"margin-left:210px;\">\r\n");
      out.write("                        <p class=\"h1 mb-3 fs-1 \" style=\"  color: #9A161F;\">Notice\r\n");
      out.write("                            <a href=\"notice_list\">\r\n");
      out.write("                                <svg style=\" margin-left:160px;\" xmlns=\"http://www.w3.org/2000/svg\" width=\"30\" height=\"30\" fill=\"currentColor\" class=\"bi bi-plus-square\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                        <path d=\"M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z\"/>\r\n");
      out.write("                        <path d=\"M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z\"/>\r\n");
      out.write("                      </svg>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Actionalbe list group -->\r\n");
      out.write("                    <div class=\"list-group \">\r\n");
      out.write("                        ");
if(noticeList!=null && noticeList.size()>0){
                        	for(int i = 0 ; i < noticeList.size() ;i++){

                        	if(i==6){
                        		break;
                        	}
                       	
      out.write("\r\n");
      out.write("                           <a href=\"");
      out.print(path );
      out.write("/NoticeView?NoticeNo=");
      out.print(noticeList.get(i).getNoticeNum() );
      out.write(" \" class=\"list-group-item list-group-item-action \">");
      out.print( noticeList.get(i).getNoticeTitile() );
      out.write("</a>\r\n");
      out.write("                       \t\r\n");
      out.write("                       \t");

                        	}
                        }
                       	
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 \" style=\"margin-right:-350px\">\r\n");
      out.write("                    <div class=\"text-center p-2 \" style=\"margin-left:140px\">\r\n");
      out.write("                        <p class=\"h1 mb-3 fs-1 \" style=\"padding-bottom: -4;  color: #9A161F;\">QnA\r\n");
      out.write("                            <a href=\"QnA_list\">\r\n");
      out.write("                                <svg style=\" margin-left:160px;\" xmlns=\"http://www.w3.org/2000/svg\" width=\"30\" height=\"30\" fill=\"currentColor\" class=\"bi bi-plus-square\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                <path d=\"M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z\"/>\r\n");
      out.write("                                <path d=\"M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z\"/>\r\n");
      out.write("                              </svg>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Actionalbe list group -->\r\n");
      out.write("                    <div class=\"list-group \">\r\n");
      out.write("                        ");
if(qnaList!=null && qnaList.size()>0){
                        	for(int i = 0 ; i < qnaList.size() ;i++){
                        		if(i==6){
                            		break;
                            	}

                        
      out.write("\r\n");
      out.write("                             <a href=\"");
      out.print(path );
      out.write("/QnaView?boardNo=");
      out.print(qnaList.get(i).getNo() );
      out.write(" \" class=\"list-group-item list-group-item-action \">");
      out.print( qnaList.get(i).getTitle() );
      out.write("</a>\r\n");
      out.write("                        \r\n");
      out.write("                        ");
 
                        	}
                        }
                        
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <br><br><br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ===================푸터 시작================-->\r\n");
      out.write("    <footer>\r\n");
      out.write("        <nav class=\"foot_custom\">\r\n");
      out.write("            <ul class=\"foot_icons_custom\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"https://facebook.com\" target=\"_blank\">\r\n");
      out.write("                        <i class=\"fa-brands fa-facebook\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"https://google.com\" target=\"_blank\">\r\n");
      out.write("                        <i class=\"fa-brands fa-google\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"https://twitter.com\" target=\"_blank\">\r\n");
      out.write("                        <i class=\"fa-brands fa-twitter\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"https://github.com\" target=\"_blank\">\r\n");
      out.write("                        <i class=\"fa-brands fa-github\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <br/><br/>\r\n");
      out.write("            <h3 style=\"color:#F4EFEA;\">COPYRIGHT ⓒ KOREA PERFORMING ARTS BOX OFFICE INFORMATION SYSTEM</h3>\r\n");
      out.write("            <h6 style=\"color:#F4EFEA;\"> When you visit or interact with our sites, services or tools, we or our authorized<br/> service providers may use cookies for storing information to help provide you with a <br/> better, faster and safer experience and for marketing purposes.</h6>\r\n");
      out.write("            <br/>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- ================== 푸터 끝 ==================-->\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js\" integrity=\"sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js\" integrity=\"sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- JS Implementing Plugins -->\r\n");
      out.write("    <script src=\"./assets/vendor/hs-mega-menu/dist/hs-mega-menu.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- JS Global Compulsory -->\r\n");
      out.write("    <script src=\"./assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"vendor/imagesloaded/imagesloaded.pkgd.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/shufflejs/dist/shuffle.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/parallax-js/dist/parallax.min.js\"></script>\r\n");
      out.write("    <!-- Vendor scrits: js libraries and plugins-->\r\n");
      out.write("    <script src=\"vendor/bootstrap/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/simplebar/dist/simplebar.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/jarallax/dist/jarallax.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/tiny-slider/dist/min/tiny-slider.js\"></script>\r\n");
      out.write("    <script src=\"vendor/flatpickr/dist/flatpickr.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/flatpickr/dist/plugins/rangePlugin.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"vendor/tiny-slider/dist/min/tiny-slider.js\"></script>\r\n");
      out.write("    <script src=\"vendor/lightgallery.js/dist/js/lightgallery.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/lg-video.js/dist/lg-video.min.js\"></script>\r\n");
      out.write("    <!-- Main theme script-->\r\n");
      out.write("    <script src=\"js/theme.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
